"use strict";
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const assert=(value,message)=>{if(!value)throw new Error(message);};
const html=read("index.html"), css=read("assets/app.css"), navigation=read("js/navigation.js"), runtime=read("js/app-runtime-config.js");
assert((html.match(/class="tabs workflow-nav"/g)||[]).length===1,"Es muss genau eine produktive Workflow-Navigation geben.");
assert(/<nav\s+aria-label="Hauptnavigation"\s+class="tabs workflow-nav"/.test(html),"Die Hauptnavigation ist nicht semantisch als nav ausgezeichnet.");
assert(!/\bon(?:click|change|input|submit|keydown)\s*=/i.test(html),"Inline-Ereignishandler sind in der Navigation vorhanden.");
const groups=[...html.matchAll(/<section class="nav-group" data-nav-group-section="([^"]+)">/g)].map(match=>match[1]);
assert(JSON.stringify(groups)===JSON.stringify(["object","billing","extras"]),`Navigationsgruppen sind falsch sortiert: ${groups.join(", ")}`);
const tabs=[...html.matchAll(/class="tab-btn nav-group-item[^"]*"[^>]*data-tab="([^"]+)"/g)].map(match=>match[1]);
const expected=["objektuebersicht","objekt","wohnungsverwaltung","wasser","mieterverwaltung","start","mieter","einnahmen","einstellungen","manuellewerte","umlage","qualitaet","vorauszahlungsanpassung","briefe","export","archiv","sicherung"];
assert(JSON.stringify(tabs)===JSON.stringify(expected),`Navigationsreihenfolge ist inkonsistent: ${tabs.join(", ")}`);
assert(tabs.length===17&&new Set(tabs).size===17,"Die Gruppennavigation muss 17 eindeutige Ziele enthalten.");
const labels=[...html.matchAll(/class="nav-item-label">([^<]+)<\/span>/g)].map(match=>match[1].replace(/&amp;/g,"&"));
assert(labels[0]==="Start","Start ist nicht der erste Navigationspunkt.");
assert(JSON.stringify(labels.slice(1,6))===JSON.stringify(["Übersicht","Objektdaten","Wohnungen","Zähler","Mieter"]),"Objektgruppe ist inkonsistent.");
assert(JSON.stringify(labels.slice(6,17))===JSON.stringify(["Übersicht","Mietverhältnisse","Vorauszahlungen","Gesamtkosten","Individuelle Werte","Abrechnungsergebnis","Prüfung","Vorauszahlungsanpassung","Briefe","Export","Archiv"]),"AP21A-Abrechnungsnavigation ist inkonsistent.");
assert(!tabs.includes("verbraeuche"),"Der alte Navigationspunkt Verbräuche erfassen ist noch sichtbar.");
assert(html.includes('data-tab="archiv"')&&html.includes('nav-archive-entry'),"Archiv ist nicht optisch vom produktiven Ablauf getrennt.");
const settings=html.match(/<button[^>]*class="sidebar-settings-dummy"[^>]*>/)?.[0]||"";
assert(settings.includes('aria-disabled="true"')&&settings.includes('data-nav-hint="Noch nicht verfügbar"')&&!settings.includes("data-ui-action"),"Einstellungen-Dummy ist inkonsistent.");
assert((html.match(/class="nav-icon-svg"/g)||[]).length>=21,"Lokales SVG-Iconsystem ist unvollständig.");
assert(!/<link[^>]+(?:fontawesome|material-icons|bootstrap-icons)|https?:\/\/[^"']+\.(?:svg|woff2?)/i.test(html),"Externe Icon- oder Schriftabhängigkeit erkannt.");
for(const token of ["--sidebar-width","--sidebar-shell","--sidebar-surface","--sidebar-text","--sidebar-icon","--sidebar-active","--sidebar-hover","--sidebar-disabled","--focus-ring","--font-ui"])assert(css.includes(token+":"),`Design-Token ${token} fehlt.`);
assert(navigation.includes('wasser:"group-object"')&&navigation.includes('archiv:"group-billing"'),"Navigationspfade sind unvollständig.");
assert(navigation.includes('node.setAttribute("aria-current", "page")')&&navigation.includes('home.classList.toggle("active", landing)'),"Aktiver Navigationszustand ist unvollständig.");
assert(!/\b(localStorage|indexedDB|caches)\b/.test(navigation)&&!/\bstate\s*[.[]/.test(navigation),"Navigationsmodul greift unzulässig auf Speicher oder Fachzustand zu.");
assert(runtime.includes('const APP_VERSION = "V99.4.24";')&&runtime.includes('const APP_VERSION_NAME = "AP21A-UI-Konsolidierung, Navigation und individuelle Werte";'),"AP21A-Laufzeitmetadaten fehlen.");
process.stdout.write("AP11-/AP21A-Navigationsprüfung abgeschlossen: Start plus 3 Gruppen, 17 Ziele und 11 konsolidierte Abrechnungsschritte sind konsistent.\n");
