"use strict";
const fs = require("node:fs");
const path = require("node:path");
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const root = path.resolve(__dirname, "..");
const renderer = fs.readFileSync(path.join(root, "js/document-renderer.js"), "utf8");
const ui = fs.readFileSync(path.join(root, "js/ui-documents.js"), "utf8");
const css = fs.readFileSync(path.join(root, "assets/app.css"), "utf8");
assert(renderer.includes("data-nk-letter-styles"), "Gemeinsame Dokument-CSS fehlt.");
assert(renderer.includes('data-document-pages="'), "Explizite Ein-/Zweiseitenangabe fehlt.");
assert(renderer.includes("<col class=\"col-balance\">"), "Neunspaltige Haupttabelle fehlt.");
assert(renderer.includes("Ihre<br>Vorauszahlung"), "Vorauszahlungen sind nicht in der Haupttabelle enthalten.");
assert(renderer.includes("prepaymentAdjustmentRequired(costRows, tenant)"), "Explizite Seitenbedingung für Vorauszahlungsanpassung fehlt.");
assert(renderer.includes("const hasSupplement = !!additionalText || prepaymentAdjustmentRequired"), "Seite 2 ist nicht ausschließlich an Zusatzinhalt gebunden.");
assert(!renderer.includes("Abrechnungsergebnis</h"), "Separate Box Abrechnungsergebnis ist noch vorhanden.");
assert(ui.includes("Zahlungstext bei Guthaben"), "Separates Guthaben-Textfeld fehlt.");
assert(ui.includes("Hinweis zum Dauerauftrag"), "Textfeld für Dauerauftrag fehlt.");
assert(ui.includes("Optionaler Abschlusstext vor der Grußformel"), "Abschlusstextfeld fehlt.");
assert(css.includes("--nk-letter-preview-scale"), "Skalierte vollständige DIN-A4-Vorschau fehlt.");
assert(css.includes("#briefe .letter-settings"), "Bedienfelder werden beim Direktdruck nicht zuverlässig ausgeblendet.");
console.log("AP13-Strukturprüfung abgeschlossen: gemeinsames DIN-A4-Dokumentmodell, kontrollierte Seitenlogik und vollständige Textfelder sind vorhanden.");
