"use strict";
const fs = require("node:fs");
const path = require("node:path");
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const root = path.resolve(__dirname, "..");
const renderer = fs.readFileSync(path.join(root, "js/document-renderer.js"), "utf8");
const ui = fs.readFileSync(path.join(root, "js/ui-documents.js"), "utf8");
const css = fs.readFileSync(path.join(root, "assets/app.css"), "utf8");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
assert(renderer.includes("data-nk-letter-styles"), "Gemeinsame Dokument-CSS fehlt.");
assert(renderer.includes('data-document-pages="'), "Explizite Ein-/Zweiseitenangabe fehlt.");
assert(renderer.includes("<col class=\"col-balance\">"), "Neunspaltige Haupttabelle fehlt.");
assert(renderer.includes("Ihre<br>Vorauszahlung"), "Vorauszahlungen sind nicht in der Haupttabelle enthalten.");
assert(renderer.includes("prepaymentAdjustmentRequired(costRows, tenant)"), "Explizite Seitenbedingung für Vorauszahlungsanpassung fehlt.");
assert(renderer.includes("const hasSupplement = !!additionalText || prepaymentAdjustmentRequired"), "Seite 2 ist nicht ausschließlich an Zusatzinhalt gebunden.");
assert(!renderer.includes("Abrechnungsergebnis</h"), "Separate Box Abrechnungsergebnis ist noch vorhanden.");
assert(ui.includes("Zahlungstext bei Guthaben"), "Separates Guthaben-Textfeld fehlt.");
assert(ui.includes("Hinweis zum Dauerauftrag"), "Textfeld für Dauerauftrag fehlt.");
assert(ui.includes("Optionaler Abschlusstext vor der Grußformel"), "Abschlusstextfeld fehlt.");
assert(ui.includes('attachShadow({ mode:"open" })') && ui.includes("briefPreviewSourceHtml"), "Isolierte druckidentische Vorschau fehlt.");
assert(css.includes("#briefe .letter-settings"), "Bedienfelder werden beim Direktdruck nicht zuverlässig ausgeblendet.");
assert(renderer.includes("AP13_RESULT_GREEN_BG"), "Grüne Guthabenkennzeichnung fehlt.");
assert(renderer.includes("margin-bottom:6mm"), "Reduzierter Abstand zwischen Detailtabelle und Hinweisbox fehlt.");
assert(renderer.includes("top:49mm"), "Seite-2-Inhalt beginnt nicht unterhalb des Informationsblocks.");
assert(renderer.includes("Anpassung der Nebenkostenvorauszahlung"), "Neue Überschrift der Vorauszahlungsanpassung fehlt.");
assert(!renderer.includes("Diese Folgeseite enthält ausschließlich"), "Überflüssiger Seite-2-Einleitungstext ist noch vorhanden.");
assert(renderer.includes("payment-notice{padding:3mm;border-left:.6mm solid"), "Blauer Akzentstrich am Zahlungshinweis fehlt.");
assert(ui.includes("mit offenen Abrechnungen verrechnet"), "Neuer Guthabentext fehlt.");
assert(ui.includes("Auf Basis Ihres individuellen Verbrauchs"), "Neuer Text zur Nebenkostenvorauszahlung fehlt.");

assert(renderer.includes("border-top:.25mm solid ${AP13_LINE}"), "Obere Begrenzung der Infobox fehlt.");
assert(renderer.includes("font-size:13pt") && renderer.includes("top:96mm"), "Betreffgroesse oder -position ist nicht korrigiert.");
assert(renderer.includes('label === "Verteilung nur auf aktive Wohneinheiten" ? "Wohneinheiten"'), "Kurzbezeichnung Wohneinheiten fehlt.");
assert(renderer.includes('<td class="money center">'), "Gesamtkostenspalte ist nicht zentriert.");
assert(renderer.includes("supplement-end{margin-top:8mm}"), "Abstand vor Abschlussblock auf Seite 2 ist nicht reduziert.");

assert(renderer.includes('if (!prepaymentAdjustmentRequired(costRows, tenant)) return "";'), "Schalter Im Brief andrucken wird im Dokumentrenderer nicht beachtet.");
assert(renderer.includes('class="continuation-hint">Weiter auf Seite 2'), "Fortsetzungshinweis für Seite 1 fehlt.");
assert(renderer.includes('data-print-mode="') && renderer.includes('is-monochrome'), "Gemeinsamer Schwarzweißmodus für Vorschau und Druck fehlt.");
assert(renderer.includes("margin:0 0 4.8mm"), "Reduzierter Abstand zwischen Anrede und Einleitung fehlt.");
assert(html.includes("Für Schwarzweißdruck optimieren") && ui.includes("schwarzweissOptimiert"), "Schwarzweißschalter fehlt.");
assert(css.includes("position:sticky") && css.includes("max-width:1100px"), "Responsive Sticky-Vorschau fehlt.");

console.log("AP13-Strukturprüfung abgeschlossen: gemeinsames DIN-A4-Dokumentmodell, kontrollierte Seitenlogik und vollständige Textfelder sind vorhanden.");
