"use strict";
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const assert=(value,message)=>{if(!value)throw new Error(message);};
const html=read("index.html"), css=read("assets/app.css"), runtime=read("js/app-runtime-config.js"), navigation=read("js/navigation.js"), controller=read("js/ui-page-controller.js"), metering=read("js/ui-metering.js"), renderer=read("js/document-renderer.js"), worker=read("service-worker.js"), project=JSON.parse(read("nk-pro-project.json"));
assert(html.includes("<title>NK-Pro V99.4.24 – AP21A UI-Konsolidierung, Navigation und individuelle Werte</title>"),"AP21A-HTML-Titel fehlt.");
assert(runtime.includes('const APP_VERSION_NAME = "AP21A-UI-Konsolidierung, Navigation und individuelle Werte";'),"AP21A-Laufzeitname fehlt.");
assert(project.versionName==="AP21A – UI-Konsolidierung, Navigationsvereinfachung und individuelle Werte","AP21A-Projektname fehlt.");
assert(project.schemaVersion===5&&project.dataLayerContractVersion===1,"Datenschema oder Datenebenenvertrag wurde verändert.");
assert(project.navigationDesignSystemVersion===5&&project.uiVisualSystemVersion===4&&project.meterInventoryDummyVersion===1,"Bestehende UI-Metadaten fehlen.");
assert(css.includes('--font-ui:"Segoe UI",Arial,sans-serif;')&&css.includes("V99.4.17 – AP14: Navigationsbereinigung und visuelles UI-System"),"AP14-UI-Grundsystem fehlt.");
assert(css.includes(".letter-page")&&css.includes("font-family:Arial, sans-serif")&&renderer.includes('font-family:Arial,"Liberation Sans",sans-serif'),"Briefschrift-Abgrenzung fehlt.");
const tabs=[...html.matchAll(/class="tab-btn nav-group-item[^"]*"[^>]*data-tab="([^"]+)"/g)].map(match=>match[1]);
const expected=["objektuebersicht","objekt","wohnungsverwaltung","wasser","mieterverwaltung","start","mieter","einnahmen","einstellungen","manuellewerte","umlage","qualitaet","vorauszahlungsanpassung","briefe","export","archiv","sicherung"];
assert(JSON.stringify(tabs)===JSON.stringify(expected),`Navigationsreihenfolge ist falsch: ${tabs.join(", ")}`);
const waterButton=html.match(/<button[^>]*data-tab="wasser"[^>]*>/)?.[0]||"";
const valuesButton=html.match(/<button[^>]*data-tab="manuellewerte"[^>]*>/)?.[0]||"";
assert(waterButton.includes('data-nav-group="object"')&&!waterButton.includes("data-requires-billing"),"Zähler-DUMMY ist nicht der Objektvorbereitung zugeordnet.");
assert(valuesButton.includes('data-nav-group="billing"')&&valuesButton.includes('data-requires-billing="true"'),"Individuelle Werte sind nicht kontextgebunden.");
assert(navigation.includes('wasser:"group-object"')&&navigation.includes('manuellewerte:"group-billing"'),"Navigationsgruppen-Mapping ist unvollständig.");
assert(runtime.includes('const BILLING_NAV_TABS = ["mieter","einnahmen","einstellungen","manuellewerte","umlage","qualitaet","vorauszahlungsanpassung","briefe","export"];'),"Konsolidierte Abrechnungstabs fehlen.");
const dummyStart=html.indexOf('<section class="tab meter-inventory-page" id="wasser">');
const valuesStart=html.indexOf('<section class="tab" id="manuellewerte">');
assert(dummyStart>=0&&valuesStart>dummyStart,"Zähler-DUMMY oder konsolidierte Werteseite fehlt.");
const dummy=html.slice(dummyStart,valuesStart);
for(const label of ["DUMMY","Wasserzähler","Wärmemengenzähler","Heizkostenverteiler","Gaszähler","Stromzähler","Zählerinventar-Übersicht"])assert(dummy.includes(label),`Zählerinventar-DUMMY enthält ${label} nicht.`);
for(const id of ["waterMeterSettings","meterCurrentSections","meterConsumptionControl","meterControlSummary"])assert(html.includes(`id="${id}"`),`Zentrale Zählerquelle ${id} fehlt auf der konsolidierten Seite.`);
assert(html.includes('id="individualValuesMeterSource"')&&html.includes('data-legacy-redirect="manuellewerte"'),"Zählerquelle oder Legacy-Weiterleitung fehlt.");
assert(controller.includes('manuellewerte:{title:"Individuelle Werte und Verbräuche erfassen"')&&controller.includes('renderContent:()=>renderIndividualValues()'),"Konsolidierte Werteseite ist nicht verdrahtet.");
assert(metering.includes('renderOverviewForTab("verbraeuche")'),"Bestehender Zählerrenderer wurde unerwartet fachlich verändert.");
assert(html.includes('id="workspaceHelpButton"')&&html.includes('id="workspaceMenuButton"')&&navigation.includes("initializeWorkspaceHeaderControls"),"Kopfaktionen fehlen.");
assert(worker.includes('const CACHE_NAME = "nk-pro-v99-4-24-ap21a";')&&worker.includes('"./js/ui-individual-values.js"'),"AP21A-PWA-App-Shell ist unvollständig.");
assert(!/<link[^>]+(?:fontawesome|material-icons|bootstrap-icons)|https?:\/\/[^"']+\.(?:svg|woff2?)/i.test(html),"Externe Icon- oder Schriftabhängigkeit erkannt.");
process.stdout.write("AP14-/AP21A-UI-Prüfung abgeschlossen: UI-System, Zähler-DUMMY, zentrale Zählerquelle und konsolidierte Werteseite sind konsistent.\n");
