"use strict";
const fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,".."); const read=f=>fs.readFileSync(path.join(root,f),"utf8"); const assert=(v,m)=>{if(!v)throw new Error(m);};
const html=read("index.html"),css=read("assets/app.css"),runtime=read("js/app-runtime-config.js"),controller=read("js/ui-page-controller.js"),navigation=read("js/navigation.js"),worker=read("service-worker.js"),project=JSON.parse(read("nk-pro-project.json")),pkg=JSON.parse(read("package.json"));
assert(pkg.version==="99.4.24"&&pkg.name==="nk-pro-v99-4-24","Aktuelle Paketversion ist inkonsistent.");
assert(project.appVersion==="99.4.24"&&project.basedOn==="99.4.23-AP21-NKP-FACH-001","Aktuelle Projektbasis ist inkonsistent.");
assert(project.schemaVersion===5&&project.dataLayerContractVersion===1&&project.documentLayoutVersion===4,"Daten- oder Dokumentvertrag wurde verändert.");
assert(project.areaDashboardVersion===2&&project.globalBillingContextVersion===2&&project.productiveDashboardVersion===1,"Dashboard-/Kontextversion fehlt.");
assert(project.pwaCacheName==="nk-pro-v99-4-24-ap21a","PWA-Cachemetadaten fehlen.");
assert(runtime.includes('const APP_VERSION = "V99.4.24";')&&worker.includes('const CACHE_NAME = "nk-pro-v99-4-24-ap21a";'),"Laufzeit- oder Cacheversion fehlt.");
const tabs=[...html.matchAll(/class="tab-btn nav-group-item[^"]*"[^>]*data-tab="([^"]+)"/g)].map(m=>m[1]);
const expected=["objektuebersicht","objekt","wohnungsverwaltung","wasser","mieterverwaltung","start","mieter","einnahmen","einstellungen","manuellewerte","umlage","qualitaet","vorauszahlungsanpassung","briefe","export","archiv","sicherung"];
assert(JSON.stringify(tabs)===JSON.stringify(expected)&&new Set(tabs).size===17,"Navigationsziele sind inkonsistent.");
assert((html.match(/data-area-dashboard=/g)||[]).length===2&&html.includes('data-area-dashboard="object"')&&html.includes('data-area-dashboard="billing"'),"Bereichs-Dashboards fehlen.");
assert(!html.includes("overview-grid")&&!controller.includes("fiktiv"),"Veraltete Vorschauwerte sind vorhanden.");
assert(controller.includes("productiveDashboardValues")&&controller.includes("billingWorkflowEntries")&&controller.includes("length===10"),"AP21A-Dashboard-Audit ist inkonsistent.");
assert(controller.includes("objectDirectEntries")&&controller.includes("length===4"),"Vier Objektdirekteinstiege werden nicht geprüft.");
for(const marker of ["data-global-billing-context","data-global-billing-object","data-global-billing-year","data-global-billing-status"])assert(html.includes(marker),`Kontextleiste enthält ${marker} nicht.`);
assert(navigation.includes('const NAV_GROUP_STORAGE_KEY = "nkpro.workflowNavigation.v4";')&&navigation.includes("let openGroups = loadOpenGroups()")&&navigation.includes("openGroups.add(key)")&&navigation.includes("openGroups.delete(key)"),"Unabhängige Navigationszustände fehlen.");
assert((html.match(/page-section__chevron-svg/g)||[]).length>=20&&css.includes(".page-section__chevron-svg"),"Lokale Klappbox-Chevrons fehlen.");
const start=html.indexOf('data-nav-group-section="billing"'),end=html.indexOf('data-nav-group-section="extras"'),fragment=html.slice(start,end);
assert((fragment.match(/nav-icon-svg/g)||[]).length>=12&&!/[😀-🙏]/u.test(fragment),"SVG-Iconsystem der Abrechnungsnavigation ist inkonsistent.");
process.stdout.write("AP17-/AP21A-Dashboardprüfung abgeschlossen: produktive Dashboards, 10 Direkteinstiege, globale Kontextleiste und unabhängige Navigation sind konsistent.\n");
