"use strict";
const fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const assert=(value,message)=>{if(!value)throw new Error(message);};
const html=read("index.html"),css=read("assets/app.css"),navigation=read("js/navigation.js"),diagnostics=read("js/diagnostics.js"),project=JSON.parse(read("nk-pro-project.json"));
assert(project.appVersion==="99.4.26"&&project.displayVersion==="V99.4.26"&&project.versionName==="AP21B1 – Navigation","AP21B1-Projektmetadaten fehlen.");
assert(project.schemaVersion===5&&project.dataLayerContractVersion===1,"Datenverträge wurden verändert.");
const groupOrder=[...html.matchAll(/data-nav-group-section="([^"]+)"/g)].map(m=>m[1]);
assert(JSON.stringify(groupOrder)===JSON.stringify(["object","billing","archive"]),"Hauptbereiche sind nicht exakt sortiert.");
const orderedLabels=[...html.matchAll(/class="nav-item-label">([^<]+)<\/span>/g)].map(m=>m[1].replace(/&amp;/g,"&"));
assert(JSON.stringify(orderedLabels)===JSON.stringify(["Objektdaten","Wohnungen","Zähler","Mietverhältnisse","Übersicht","Mietverhältnisse","Vorauszahlungen","Gesamtkosten","Individuelle Werte","Abrechnungsergebnis","Prüfung & Freigabe","Briefe","Archivübersicht"]),"Sichtbare Menübezeichnungen sind nicht exakt.");
assert(!orderedLabels.includes("Vorauszahlungsanpassung")&&!orderedLabels.includes("Export")&&!orderedLabels.includes("Start"),"Nicht freigegebene sichtbare Einträge sind vorhanden.");
assert(css.includes("/* V99.4.26 – AP21B1: linke Navigation nach verbindlicher Referenz */")&&!css.includes("/* V99.4.25 – Navigation exakt nach freigegebenem Mockup */"),"Abgebrochener Navigationsstand wurde nicht sauber ersetzt.");
for(const token of ["--sidebar-width:256px","border-radius:12px 12px 0 0","background:linear-gradient(90deg,#f1f6ff 0%,#e8f1ff 100%)","outline:2px solid #176fd1","@media (max-width:980px)"])assert(css.includes(token),`AP21B1-Navigationsstil fehlt: ${token}`);
assert(navigation.includes('nkpro.workflowNavigation.v6')&&navigation.includes('"group-archive"')&&navigation.includes('archiv:"group-archive"'),"Accordion- oder Archivnavigation ist nicht integriert.");
assert(html.includes('class="sidebar-brand-home" data-ui-action="navigation.showLanding"')&&html.includes('data-ui-action="navigation.showLanding" id="sidebarCollapseTop"'),"Logo- oder Zurück-Funktion zur Arbeitsweiche fehlt.");
assert(diagnostics.includes('groups.join("|") !== "object|billing|archive"')&&diagnostics.includes('Logo- oder Zurück-Funktion zur Arbeitsweiche fehlt'),"Interne AP21B1-Navigationsdiagnose fehlt.");
for(const tab of ["objektuebersicht","vorauszahlungsanpassung","export","sicherung"])assert(html.includes(`id="${tab}"`),`Bestehender Seitenschlüssel ${tab} fehlt.`);
process.stdout.write("AP21B1-Strukturprüfung bestanden: Referenzbreite, Reihenfolge, eigener Archivbereich, Zustände und Kompatibilität sind statisch abgesichert.\n");
