"use strict";
const fs=require("node:fs");
const assert=require("node:assert/strict");
const html=fs.readFileSync("index.html","utf8");
const css=fs.readFileSync("assets/app.css","utf8");
const js=fs.readFileSync("js/ui-individual-values.js","utf8");
assert.match(html,/id="manuellewerte"/);
assert.match(html,/id="individualValuesStatusHeading"/);
assert.match(html,/id="individualValuesListHeading"/);
assert.match(html,/data-individual-result-count/);
assert.match(html,/id="individualValuesList"/);
assert.match(html,/id="individualValuesMeterSource"/);
for (const filter of ["all","open","error","complete","none"]) assert.match(html,new RegExp(`data-individual-filter="${filter}"`));
assert.match(css,/AP21C – klare Arbeitsstruktur/);
assert.match(css,/\.individual-values-overview/);
assert.match(css,/\.individual-values-workspace/);
assert.match(css,/\.individual-cost-card__summary:focus-visible/);
assert.match(js,/data-individual-result-count/);
assert.match(js,/NKProBillingWorkflow\.setIndividualValuesImport/);
assert.match(js,/NKProBillingWorkflow\.resetIndividualValues/);
console.log("AP21C Struktur- und Kompatibilitätsprüfung bestanden.");
