"use strict";
const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");
const root = path.resolve(__dirname,"..");
const read = file => fs.readFileSync(path.join(root,file),"utf8");
const html = read("index.html");
const css = read("assets/app.css");
const project = JSON.parse(read("nk-pro-project.json"));
const pkg = JSON.parse(read("package.json"));
const page = html.slice(html.indexOf('<section class="tab" id="manuellewerte"'),html.indexOf('<section class="tab" id="umlage"'));
assert.match(page,/nk-ui-page-shell--wide/);
assert.match(page,/data-page-shell="wide"/);
assert.doesNotMatch(page,/nk-ui-page-shell--default/);
assert.match(css,/AP22F10G-B Korrektur 2/);
assert.match(css,/#manuellewerte \.individual-values-page\{max-width:var\(--nk-ui-shell-max-wide,1440px\)\}/);
assert.match(css,/#manuellewerte \.individual-values-consumption-table,[\s\S]*?individual-values-manual-table\{min-width:0;table-layout:fixed\}/);
assert.match(css,/@media\(max-width:980px\)\{[\s\S]*?individual-values-consumption-table\{min-width:1080px;table-layout:auto\}/);
assert.match(css,/#manuellewerte \.individual-values-table-wrap\{[^}]*width:calc\(100% - 32px\)[^}]*margin:14px 16px/);
assert.match(css,/individual-values-meter-dot\.is-cold-water\{[^}]*#1976c8/);
assert.match(css,/individual-values-meter-dot\.is-hot-water\{[^}]*#d5282f/);
assert.match(css,/individual-values-input-wrap\.is-transferred[^}]*background:#eef1f4/);
assert.equal(project.displayVersion,"V99.4.60");
assert.equal(project.individualValuesPageCorrectionVersion,2);
assert.equal(project.individualValuesDesktopTableFitVersion,1);
assert.equal(pkg.version,"99.4.60");
assert.match(read("service-worker.js"),/99\.4\.60-ap22f10g-b-k2/);
console.log("AP22F10G-B Korrektur 2 static checks: PASS");
