"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const html=read("index.html");
const css=read("assets/app.css");
const ui=read("js/ui-navigation-pages.js");
const runtime=read("js/app-runtime-config.js");
const worker=read("service-worker.js");
const register=read("js/service-worker-register.js");
const start=html.slice(html.indexOf('<section class="tab" id="start"'),html.indexOf('<section class="tab"',html.indexOf('<section class="tab" id="start"')+20));
assert.ok(start,"section#start fehlt");
assert.doesNotMatch(start,/<details[^>]*id="billingPeriodSection"/,"Zeitraum-Klappbox ist noch vorhanden");
assert.match(start,/id="billingPeriodSettings"[^>]*>Abrechnungszeitraum bearbeiten<\/button>/,"klar bezeichnete Zeitraumaktion fehlt");
assert.match(start,/class="modal-backdrop[^\"]*"[^>]*id="billingPeriodSection"/,"separater Zeitraumdialog fehlt");
assert.match(start,/data-ui-change="billing\.setPeriod"[^>]*id="billingPeriodStartValue"/,"Beginn verwendet nicht den bestehenden Schreibweg");
assert.match(start,/data-ui-change="billing\.setPeriod"[^>]*id="billingPeriodEndValue"/,"Ende verwendet nicht den bestehenden Schreibweg");
assert.match(start,/data-ui-action="billing\.syncPeriodYear"/,"bestehender Jahresabgleich fehlt");
assert.match(css,/#start \.billing-overview-messages:not\(:has\(#appStatusBox:not\(:empty\),#appFeedbackBox:not\(:empty\)\)\)\{display:none!important\}/,"leerer Hinweisbereich wird nicht ausgeblendet");
assert.match(css,/\.workflow-nav\.archive-nav \[data-nav-group-section="object"\]\{display:block!important\}/,"Objekt vorbereiten bleibt im Archivmodus nicht sichtbar");
assert.match(ui,/function openBillingPeriodEditor\(\)/);
assert.match(ui,/function closeBillingPeriodEditor\(\)/);
assert.doesNotMatch(ui,/const modeLabel = editable \? "Bearbeitbar" : "Nur ansehen"/);
assert.match(ui,/trigger\.textContent = editable \? "Abrechnungszeitraum bearbeiten" : "Abrechnungszeitraum anzeigen"/);
assert.match(runtime,/const APP_VERSION = "V99\.4\.41";/,"Produktversion wurde unerwartet geändert");
assert.match(runtime,/const DATA_SCHEMA_VERSION = 5;/,"Datenschema wurde verändert");
for(const source of [html,worker,register])assert.match(source,/99\.4\.41-ap22f6b-k1/,"Korrektur-Cachekennung fehlt");
console.log("AP22F6B Korrektur 1 static: PASS");
