"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const os=require("node:os");
const path=require("node:path");
const {chromium}=require("@playwright/test");
const {openFreshApp,loadFixture,attachRuntimeGuards}=require("./test-helpers.cjs");
const root=path.resolve(__dirname,"..");
const screenshots=process.env.AP22F6B_SCREENSHOT_DIR||path.join(os.tmpdir(),"NK-Pro_AP22F6B_Screenshots");
fs.rmSync(screenshots,{recursive:true,force:true});fs.mkdirSync(screenshots,{recursive:true});
function shot(name){return path.join(screenshots,name);}
async function fresh(browser,viewport={width:1440,height:1000}){const page=await browser.newPage({viewport,locale:"de-DE",timezoneId:"Europe/Berlin"});const runtime=attachRuntimeGuards(page);await openFreshApp(page);await loadFixture(page,"standardfall.json");await page.evaluate(()=>{switchToTab("start");renderAll({tabIds:["start"],reason:"ap22f6b-browser"});});await page.waitForSelector("#start.active");return {page,runtime};}
async function noPageOverflow(page){const d=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,bw:document.body.scrollWidth}));assert.ok(d.sw<=d.cw+1,`Dokument-Overflow ${JSON.stringify(d)}`);assert.ok(d.bw<=d.cw+1,`Body-Overflow ${JSON.stringify(d)}`);}
async function actionGroupsOneLine(page){const values=await page.locator("#startArchiveTable .billing-actions").evaluateAll(groups=>groups.map(g=>{const r=g.getBoundingClientRect();const buttons=[...g.querySelectorAll("button")].map(b=>b.getBoundingClientRect());return {height:r.height,scrollWidth:g.scrollWidth,clientWidth:g.clientWidth,whiteSpace:getComputedStyle(g).whiteSpace,topSpread:buttons.length?Math.max(...buttons.map(x=>x.top))-Math.min(...buttons.map(x=>x.top)):0};}));assert.ok(values.length>=1);for(const v of values){assert.equal(v.whiteSpace,"nowrap");assert.ok(v.topSpread<1,`Aktionsgruppe umgebrochen: ${JSON.stringify(v)}`);assert.ok(v.height<=36,`Aktionsgruppe zu hoch: ${JSON.stringify(v)}`);assert.ok(v.scrollWidth<=v.clientWidth+1,`interner Aktionsüberlauf: ${JSON.stringify(v)}`);}}
async function verifyIcons(page){const buttons=page.locator("#startArchiveTable .billing-overview-action");assert.ok(await buttons.count()>=6);for(let i=0;i<await buttons.count();i++){const b=buttons.nth(i);const info=await b.evaluate(node=>({title:node.title,label:node.getAttribute("aria-label"),iconOnly:node.dataset.iconOnly,svgHidden:node.querySelector("svg")?.getAttribute("aria-hidden"),visibleText:[...node.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE&&n.textContent.trim()).map(n=>n.textContent.trim()),w:node.getBoundingClientRect().width,h:node.getBoundingClientRect().height}));assert.equal(info.title,info.label);assert.ok(info.title);assert.equal(info.iconOnly,"true");assert.equal(info.svgHidden,"true");assert.deepEqual(info.visibleText,[]);assert.ok(Math.abs(info.w-info.h)<1);}}
async function showStart(page){await page.evaluate(()=>{switchToTab("start");renderAll({tabIds:["start"],reason:"ap22f6b-return"});});await page.waitForSelector("#start.active");}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||"/usr/bin/chromium",args:["--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage"]});try{
 // Desktop structure, filters, search, keyboard, create dialog.
 {const {page,runtime}=await fresh(browser);assert.equal(await page.locator("#start h1").count(),1);assert.equal(await page.locator("#startArchiveTable thead th").count(),7);assert.equal(await page.locator('#startArchiveTable tr[data-billing-record="true"]').count(),5);assert.equal(await page.locator('#startArchiveTable [data-record-kind="current"]').count(),1);assert.equal(await page.locator('#startArchiveTable [data-record-kind="archive"]').count(),4);assert.equal(await page.locator('#start [data-area-dashboard="billing"]').count(),0);assert.equal(await page.locator('#start button[data-ui-action="system.runSelfTest"]').count(),0);assert.equal(await page.locator('#start [data-ap22f6b-diagnostics-compat]').isVisible(),false);assert.equal(await page.locator('#startArchiveTable [data-ui-action*="delete"]').count(),0);await verifyIcons(page);await actionGroupsOneLine(page);await noPageOverflow(page);const shell=await page.locator('.billing-overview-table-shell').evaluate(n=>({sw:n.scrollWidth,cw:n.clientWidth}));assert.ok(shell.sw<=shell.cw+1,"Desktop-Tabelle passt nicht vollständig");
  const labels=await page.locator('#startArchiveTable .current-record-row .billing-overview-action').evaluateAll(bs=>bs.map(b=>b.getAttribute('aria-label')));assert.deepEqual(labels,["Bearbeiten","Ansehen","Abschließen","Archivieren"]);
  await page.locator('[data-billing-overview-filter="archive"]').click();assert.equal(await page.locator('#startArchiveTable tr[data-billing-record="true"]:visible').count(),4);assert.equal(await page.locator('[data-billing-overview-results]').textContent(),'4 von 5 Abrechnungen');
  await page.locator('#billingOverviewSearch').fill('2023');assert.equal(await page.locator('#startArchiveTable tr[data-billing-record="true"]:visible').count(),1);await page.locator('#billingOverviewSearch').fill('amr5');assert.equal(await page.locator('#startArchiveTable tr[data-billing-record="true"]:visible').count(),4);await page.locator('#billingOverviewReset').click();assert.equal(await page.locator('#startArchiveTable tr[data-billing-record="true"]:visible').count(),5);
  const stateBefore=await page.evaluate(()=>JSON.stringify(state));await page.locator('[data-billing-overview-filter="all"]').focus();await page.keyboard.press('Tab');assert.equal(await page.locator('[data-billing-overview-filter="current"]').evaluate(n=>document.activeElement===n),true);const focus=await page.locator('[data-billing-overview-filter="current"]').evaluate(n=>({outline:getComputedStyle(n).outlineStyle,shadow:getComputedStyle(n).boxShadow}));assert.ok(focus.outline!=="none"||focus.shadow!=="none");await page.locator('#startArchiveTable .current-record-row [aria-label="Bearbeiten"]').focus();await page.keyboard.press('Tab');assert.equal(await page.locator('#startArchiveTable .current-record-row [aria-label="Ansehen"]').evaluate(n=>document.activeElement===n),true);const iconFocus=await page.locator('#startArchiveTable .current-record-row [aria-label="Ansehen"]').evaluate(n=>getComputedStyle(n).outlineStyle);assert.notEqual(iconFocus,"none");assert.equal(await page.evaluate(()=>JSON.stringify(state)),stateBefore,"Filter/Fokus verändert Fachdaten");
  await page.locator('[data-ui-action="billing.openCreateModal"]').first().click();assert.equal(await page.locator('#billingCreateModal').evaluate(n=>n.classList.contains('show')),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#billingCreateModal').evaluate(n=>n.classList.contains('show')),false);
  await page.screenshot({path:shot('01_desktop_uebersicht_geschlossen.png'),fullPage:true});runtime.assertClean();await page.close();}
 // Bearbeiten, Schließen, Rücksprung auf letzten Schritt.
 {const {page,runtime}=await fresh(browser);await page.locator('#startArchiveTable .current-record-row [aria-label="Bearbeiten"]').click();assert.equal(await page.evaluate(()=>NK_PRO_MODULES.billingContext.snapshot().mode),"edit");assert.equal(await page.locator('[data-global-billing-context]').isVisible(),true);assert.equal((await page.locator('[data-global-billing-context]').innerText()).includes('Modus'),false);await page.evaluate(()=>{switchToTab('einstellungen');NK_PRO_MODULES.billingContext.rememberStep('einstellungen');switchToTab('start');});await showStart(page);assert.equal(await page.locator('#startArchiveTable .current-record-row').evaluate(n=>n.classList.contains('is-open-context')),true);await page.screenshot({path:shot('02_desktop_bearbeiten.png'),fullPage:true});await page.locator('[data-global-billing-close]').click();assert.equal(await page.evaluate(()=>NK_PRO_MODULES.billingContext.snapshot().mode),"closed");await page.locator('#startArchiveTable .current-record-row [aria-label="Bearbeiten"]').click();assert.equal(await page.locator('#einstellungen').evaluate(n=>n.classList.contains('active')),true,"letzter Arbeitsschritt wurde nicht wiederhergestellt");runtime.assertClean();await page.close();}
 // Nur ansehen: große Notice, Suche/Filter möglich, Schreibaktionen gesperrt.
 {const {page,runtime}=await fresh(browser);await page.locator('#startArchiveTable .current-record-row [aria-label="Ansehen"]').click();assert.equal(await page.evaluate(()=>NK_PRO_MODULES.billingContext.snapshot().mode),"view");await showStart(page);const notice=page.locator('#start .billing-readonly-notice');assert.equal(await notice.isVisible(),true);const overlap=await page.evaluate(()=>{const n=document.querySelector('#start .billing-readonly-notice').getBoundingClientRect(),c=document.querySelector('#start .billing-overview-card').getBoundingClientRect();return n.bottom>c.top+1;});assert.equal(overlap,false,"Schreibschutz-Notice überlagert Inhalt");assert.equal((await page.locator('[data-global-billing-context]').innerText()).includes('Modus'),false);await page.locator('#billingOverviewSearch').fill('2024');assert.equal(await page.locator('#startArchiveTable tr[data-billing-record="true"]:visible').count(),1);await page.screenshot({path:shot('03_desktop_nur_ansehen.png'),fullPage:true});runtime.assertClean();await page.close();}
 // Archivviewer und Korrekturweg. Der bestehende Handler öffnet den archivierten Kontext am gespeicherten Arbeitsschritt.
 {const {page,runtime}=await fresh(browser);await page.locator('#startArchiveTable .archive-record-row').first().locator('[aria-label="Ansehen"]').click();assert.equal(await page.evaluate(()=>NK_PRO_MODULES.billingContext.snapshot().mode),"view");assert.equal(await page.locator('[data-global-billing-status]').textContent(),'Archiviert');assert.equal(await page.locator('#mieter').evaluate(n=>n.classList.contains('active')),true,"Archivviewer öffnet nicht den bestehenden Ziel-Arbeitsschritt");const archiveNotice=page.locator('#mieter .billing-readonly-notice');assert.equal(await archiveNotice.isVisible(),true);assert.equal(await archiveNotice.locator('[data-ui-action="billing.switchToEdit"]').count(),0);assert.equal((await page.locator('[data-global-billing-context]').innerText()).includes('Modus'),false);await page.screenshot({path:shot('04_desktop_archiviert.png'),fullPage:true});await page.locator('[data-global-billing-close]').click();await showStart(page);await page.evaluate(()=>{window.confirm=()=>true;window.prompt=()=>"KORREKTUR";});await page.locator('#startArchiveTable .archive-record-row').first().locator('[aria-label="Zur Korrektur öffnen"]').click();assert.equal(await page.evaluate(()=>NK_PRO_MODULES.billingContext.snapshot().mode),"edit");runtime.assertClean();await page.close();}
 // Aktionshandler für Abschluss/Archiv unverändert an die zentrale Actionschicht gebunden.
 {const {page,runtime}=await fresh(browser);await page.evaluate(()=>{window.__ap22f6bAlerts=[];window.alert=message=>window.__ap22f6bAlerts.push(String(message));window.confirm=()=>true;});await page.locator('#startArchiveTable .current-record-row [aria-label="Abschließen"]').click();assert.equal(await page.evaluate(()=>!!state.meta.currentBillingFinalized),false,"Blockierte Abrechnung wurde unerwartet finalisiert");assert.ok((await page.evaluate(()=>window.__ap22f6bAlerts.join(' '))).includes('Finalisierung nicht möglich'));await showStart(page);const archiveCount=await page.evaluate(()=>(state.jahresArchiv||[]).length);await page.locator('#startArchiveTable .current-record-row [aria-label="Archivieren"]').click();assert.equal(await page.evaluate(()=>(state.jahresArchiv||[]).length),archiveCount+1);assert.equal(await page.locator('#archiv').evaluate(n=>n.classList.contains('active')),true,"Archivaktion hat das bestehende Archivziel nicht geöffnet");runtime.assertClean();await page.close();}
 // Finalisierter aktueller Datensatz: bestehende Statuslogik zeigt ausschließlich Archiv aktualisieren.
 {const {page,runtime}=await fresh(browser);await page.evaluate(()=>{state.meta.currentBillingFinalized=true;state.meta.currentBillingFinalizationKey=String(state.meta.abrechnungsjahr||currentAbrechnungsjahr()||'')+'|'+String(state.meta.abrechnungsbeginn||'')+'|'+String(state.meta.abrechnungsende||'');state.meta.currentBillingFinalizedAt=new Date().toISOString();renderStart();});const labels=await page.locator('#startArchiveTable .current-record-row .billing-overview-action').evaluateAll(bs=>bs.map(b=>b.getAttribute('aria-label')));assert.deepEqual(labels,["Bearbeiten","Ansehen","Archiv aktualisieren"]);assert.equal(await page.locator('#startArchiveTable .current-record-row [aria-label="Abschließen"]').count(),0);assert.equal(await page.locator('#startArchiveTable .current-record-row [aria-label="Archivieren"]').count(),0);const disabled=await page.locator('#startArchiveTable .current-record-row [aria-label="Archiv aktualisieren"]').evaluate(node=>{node.disabled=true;node.setAttribute('aria-disabled','true');const style=getComputedStyle(node);return {disabled:node.disabled,aria:node.getAttribute('aria-disabled'),cursor:style.cursor,opacity:style.opacity};});assert.equal(disabled.disabled,true);assert.equal(disabled.aria,'true');assert.equal(disabled.cursor,'not-allowed');assert.ok(Number(disabled.opacity)<1);runtime.assertClean();await page.close();}
 // Responsive 620, 390 und Zoomäquivalent 720.
 for(const v of [{width:620,height:900,name:'05_schmal_620.png'},{width:390,height:844,name:'06_schmal_390.png'},{width:720,height:900,name:'09_zoom_200_prozent_aequivalent.png'}]){const {page,runtime}=await fresh(browser,{width:v.width,height:v.height});await noPageOverflow(page);await actionGroupsOneLine(page);const shell=await page.locator('.billing-overview-table-shell').evaluate(n=>({sw:n.scrollWidth,cw:n.clientWidth}));assert.ok(shell.sw>shell.cw,"schmale Tabelle benötigt internen horizontalen Scroll");await page.locator('.billing-overview-table-shell').evaluate(n=>n.scrollLeft=n.scrollWidth);assert.equal(await page.locator('#startArchiveTable .current-record-row [aria-label="Archivieren"]').isVisible(),true);await page.screenshot({path:shot(v.name),fullPage:true});runtime.assertClean();await page.close();}
 // Leerzustand.
 {const {page,runtime}=await fresh(browser);await page.evaluate(()=>{state.jahresArchiv=[];state.meta.currentBillingArchivedOnly=true;state.meta.currentBillingClosedAfterArchive=true;delete state.meta.currentBillingCreatedByUser;delete state.meta.currentBillingExplicitlyCreated;delete state.meta.preparedFromPreviousYear;delete state.meta.currentBillingFinalized;delete state.meta.currentBillingFinalizedAt;renderStart();});assert.equal(await page.locator('#startArchiveTable tr[data-billing-record="true"]').count(),0);assert.equal(await page.locator('#startArchiveTable .billing-overview-empty').isVisible(),true);assert.ok((await page.locator('#startArchiveTable').innerText()).includes('Noch keine Abrechnung angelegt'));await page.screenshot({path:shot('07_leerzustand.png'),fullPage:true});runtime.assertClean();await page.close();}
 // Keine Treffer und erzwungener Renderfehler im Dokumentfluss.
 {const {page,runtime}=await fresh(browser);await page.locator('#billingOverviewSearch').fill('kein-treffer-xyz');assert.equal(await page.locator('.billing-overview-no-results').isVisible(),true);await page.locator('[data-billing-overview-empty-reset]').click();assert.equal(await page.locator('#startArchiveTable tr[data-billing-record="true"]:visible').count(),5);await page.evaluate(()=>{window.__ap22f6bOriginalBuild=buildBillingRecordsTableHtml;buildBillingRecordsTableHtml=()=>{throw new Error('Erzwungener AP22F6B-Renderfehler')};renderStart();});assert.equal(await page.locator('#start .billing-overview-render-error').isVisible(),true);await noPageOverflow(page);await page.screenshot({path:shot('08_fehlerzustand.png'),fullPage:true});await page.evaluate(()=>{buildBillingRecordsTableHtml=window.__ap22f6bOriginalBuild;renderStart();});runtime.assertClean();await page.close();}
 console.log(`AP22F6B browser: PASS (${screenshots})`);
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
