"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=file=>fs.readFileSync(file,"utf8");
const pkg=JSON.parse(read("package.json"));
const lock=JSON.parse(read("package-lock.json"));
const manifest=JSON.parse(read("manifest.webmanifest"));
const project=JSON.parse(read("nk-pro-project.json"));
const runtime=read("js/app-runtime-config.js");
const worker=read("service-worker.js");
const register=read("js/service-worker-register.js");
assert.equal(pkg.version,"99.4.45");
assert.equal(pkg.name,"nk-pro-v99-4-45");
assert.equal(lock.version,"99.4.45");
assert.equal(lock.packages[""].version,"99.4.45");
assert.equal(manifest.version,"99.4.45");
assert.equal(manifest.buildId,"99.4.45-ap22f10b");
assert.equal(project.appVersion,"99.4.45");
assert.equal(project.displayVersion,"V99.4.45");
assert.equal(project.runtimeBuildId,"99.4.45-ap22f10b");
assert.equal(project.schemaVersion,5);
assert.match(runtime,/const APP_VERSION = "V99\.4\.45"/);
assert.match(runtime,/AP22F10B-Individuelle-Werte/);
assert.match(worker,/99\.4\.45-ap22f10b/);
assert.match(register,/99\.4\.45-ap22f10b/);
console.log("AP22F10B Release-Metadaten: PASS");
