"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const crypto=require("node:crypto");
const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const sha=file=>crypto.createHash("sha256").update(fs.readFileSync(path.join(root,file))).digest("hex");
function extractSection(source,id){const start=new RegExp(`<section\\b[^>]*\\bid="${id}"[^>]*>`,"i").exec(source);assert.ok(start,`section#${id} fehlt`);const tags=/<\/?section\b[^>]*>/ig;tags.lastIndex=start.index+start[0].length;let depth=1,match;while((match=tags.exec(source))){depth+=match[0][1]==="/"?-1:1;if(depth===0)return source.slice(start.index,tags.lastIndex);}throw new Error(`section#${id} unvollständig`)}
function extractFunction(source,name,next){const a=source.indexOf(`function ${name}(`);assert.ok(a>=0,`${name} fehlt`);const b=next?source.indexOf(`function ${next}(`,a):source.length;assert.ok(b>a);return source.slice(a,b)}
const html=read("index.html"),renderer=read("js/ui-navigation-pages.js"),controller=read("js/ui-page-controller.js"),css=read("assets/app.css"),reference=read("ui-reference/index.html"),referenceCss=read("ui-reference/reference.css");
const meter=extractSection(html,"wasser");assert.equal((meter.match(/class="meter-inventory-card /g)||[]).length,5);assert.ok(meter.includes('id="meterInventoryDummyTable"'));assert.equal((meter.match(/data-ui-action=/g)||[]).length,0,"DUMMY-Seite enthält produktive Aktionen");
const tenant=extractSection(html,"mieterverwaltung");
for(const id of ["tenantManagementSearch","tenantManagementUnitFilter","tenantManagementStatusFilter","tenantManagementReset","startTenantTable"])assert.ok(tenant.includes(`id="${id}"`),`${id} fehlt`);
assert.ok(!tenant.includes('id="startTenantArchiveTable"')&&!tenant.includes('masterTenantArchiveSection'),"separate Legacy-Archivtabelle verblieben");
assert.equal((tenant.match(/data-tenant-view-button=/g)||[]).length,2,"Umschalter Aktiv/Archiv fehlt");
assert.ok(tenant.includes('data-ui-action="object.addMasterTenancy"'));
const fn=extractFunction(renderer,"renderStartTenantManagement","renderMeterInventoryDummyPage");
assert.equal((fn.match(/setMasterNested\(\\'mieter\\'/g)||[]).length,12,"zwölf bestehende Pflegefelder nicht vollständig erhalten");
for(const field of ["wohnung","name","einzug","auszug","abrechnungRolle","geschlecht","standardanrede","strasse","plz","ort","telefon","email"])assert.ok(fn.includes(`\\'${field}\\'`),`Feld fehlt: ${field}`);
for(const token of ["data-tenant-toggle","tenant-management-detail-row","tenant-detail-panel--readonly","data-tenant-view-button","object.archiveMasterTenancy","object.restoreMasterTenancy"])assert.ok(fn.includes(token),`Korrekturmerkmal fehlt: ${token}`);
assert.ok(fn.includes('statusFilterEl.hidden = view === "archive"')&&fn.includes('addButton.hidden = view === "archive"'),"Archivwerkzeuge nicht klar getrennt");
assert.ok(fn.includes('billingContext.isReadOnly()')&&fn.includes('readOnlyControl'),"Nur-Ansehen-Schutz fehlt");
for(const forbidden of ["saveState(","localStorage","migration","kostenarten","vorauszahlungen","zaehlerDaten"])assert.ok(!fn.toLowerCase().includes(forbidden.toLowerCase()),`unerlaubter Fachbezug: ${forbidden}`);
assert.ok(controller.includes('disableSaveInReadOnly:true'));
for(const rule of ["tenant-view-switch","tenant-management-detail-row","tenant-detail-panel","tenant-archive-detail-grid","#mieterverwaltung #startTenantTable.tenant-management-table"])assert.ok(css.includes(rule),`CSS-Regel fehlt: ${rule}`);
assert.ok(css.includes('min-width:900px!important')&&css.includes('overflow-x:auto'));
assert.ok(reference.includes('AP22F5B Korrektur 1 · verbindliche Zielkomponente')&&reference.includes('kompakte Übersicht und gemeinsame Archivansicht'));
assert.ok(referenceCss.includes('AP22F5B Korrektur 1 – kompakte Mietverhältnisse'));
assert.ok(html.includes('<strong data-app-version="">V99.4.40</strong>'));assert.ok(read("js/app-runtime-config.js").includes('const APP_VERSION = "V99.4.40";'));
const protectedHashes=JSON.parse(read("AP22F5B_PROTECTED_HASHES.json"));for(const [file,expected] of Object.entries(protectedHashes))assert.equal(sha(file),expected,`geschützte Datei verändert: ${file}`);
console.log(`AP22F5B Korrektur 1 static: PASS (${Object.keys(protectedHashes).length} Schutz-Hashes)`);
