"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const {chromium}=require("@playwright/test");
const {openFreshApp,loadFixture,attachRuntimeGuards}=require("./test-helpers.cjs");
const shots=process.env.AP22F7B_SCREENSHOT_DIR||path.join(process.cwd(),"AP22F7B_Screenshots");
fs.rmSync(shots,{recursive:true,force:true});fs.mkdirSync(shots,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||"/usr/bin/chromium",args:["--no-sandbox","--disable-dev-shm-usage"]});
 const context=await browser.newContext({viewport:{width:1440,height:1000},locale:"de-DE",timezoneId:"Europe/Berlin",serviceWorkers:"block"});
 const page=await context.newPage();const runtime=attachRuntimeGuards(page);
 try{
  await openFreshApp(page);await loadFixture(page,"standardfall.json");
  await page.evaluate(()=>{NK_PRO_MODULES.billingContext.open({recordKey:"current",recordType:"current",label:"2025"},NK_PRO_MODULES.billingContext.MODES.EDIT);document.documentElement.dataset.billingExplicitlyOpened="true";switchToTab("mieter");renderAll({forceAll:true,reason:"ap22f7b"});});
  await page.waitForSelector("#mieter.active");
  assert.equal(await page.locator("#mieter h1").innerText(),"Mietverhältnisse");
  assert.equal(await page.locator("#mieter details").count(),0);
  assert.equal(await page.locator("#mieter #mieterTable thead th").count(),8);
  assert.equal(await page.locator("#mieter #wohnungenTable thead th").count(),6);
  assert.ok(await page.locator("#mieter #mieterTable tbody tr").count()>=5);
  await page.locator("#mieter .billing-tenant-detail-button").first().click();
  assert.equal(await page.locator("#mieter .billing-tenant-detail").count(),1);
  assert.match(await page.locator("#mieter .billing-tenant-detail").innerText(),/Adresse und Kontakt/);
  await page.locator("#billingTenantSearch").fill("Zimmermann");await page.waitForTimeout(80);
  assert.match(await page.locator("#billingTenantResults").innerText(),/^1 von/);
  await page.evaluate(()=>billingTenantReset("tenants"));
  await page.waitForTimeout(50);
  const overflow=await page.evaluate(()=>({doc:document.documentElement.scrollWidth-document.documentElement.clientWidth,table:document.querySelector("#mieter .billing-tenant-table-shell").scrollWidth-document.querySelector("#mieter .billing-tenant-table-shell").clientWidth}));
  assert.ok(overflow.doc<=1,JSON.stringify(overflow));
  await page.screenshot({path:path.join(shots,"01_desktop_bearbeiten_detail.png")});
  await page.locator("#mieter .billing-tenant-detail-button").first().click();
  await page.waitForTimeout(50);
  assert.equal(await page.locator("#mieter .billing-tenant-detail").count(),0);
  await page.screenshot({path:path.join(shots,"02_desktop_bearbeiten_kompakt.png")});
  await page.locator("#billingTenantSearch").fill("Kein Treffer AP22F7B");await page.waitForTimeout(60);
  assert.equal(await page.locator("#mieter .billing-tenant-empty").count(),1);
  await page.screenshot({path:path.join(shots,"06_keine_treffer.png")});
  await page.evaluate(()=>billingTenantReset("tenants"));await page.waitForTimeout(50);
  await page.evaluate(()=>{window.__ap22f7bData={mieter:JSON.parse(JSON.stringify(state.mieter)),wohnungen:JSON.parse(JSON.stringify(state.wohnungen))};state.mieter=[];state.wohnungen=[];renderWohnungen();});
  assert.match(await page.locator("#mieter").innerText(),/Keine Mietverhältnisse|Keine Wohnungen/);
  await page.screenshot({path:path.join(shots,"07_leerzustand.png")});
  await page.evaluate(()=>{state.mieter=window.__ap22f7bData.mieter;state.wohnungen=window.__ap22f7bData.wohnungen;renderWohnungen();delete window.__ap22f7bData;});
  await page.setViewportSize({width:720,height:900});await page.screenshot({path:path.join(shots,"08_zoom_200_prozent_aequivalent.png")});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=1);
  await page.setViewportSize({width:620,height:900});await page.screenshot({path:path.join(shots,"04_schmal_620.png")});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=1);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(shots,"05_schmal_390.png")});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=1);
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>{NK_PRO_MODULES.billingContext.close();NK_PRO_MODULES.billingContext.open({recordKey:"current",recordType:"current",label:"2025"},NK_PRO_MODULES.billingContext.MODES.VIEW);switchToTab("mieter");renderAll({forceAll:true,reason:"readonly"});});
  assert.equal(await page.locator("#mieter .billing-readonly-notice").count(),1);
  assert.equal(await page.locator("#billingTenantSearch").isEditable(),true);
  assert.equal(await page.locator("#mieter #wohnungenTable select").first().isDisabled(),true);
  assert.equal(await page.locator("#mieter [data-ui-action='object.applyMasterDataToBilling']").isVisible(),false);
  await page.screenshot({path:path.join(shots,"03_desktop_nur_ansehen.png")});
  await page.evaluate(()=>{const box=document.getElementById("billingTenantError");box.hidden=false;box.scrollIntoView({block:"center"});});
  assert.equal(await page.locator("#billingTenantError").isVisible(),true);
  await page.screenshot({path:path.join(shots,"09_fehlerzustand.png")});
  runtime.assertClean();console.log("AP22F7B browser: PASS");
 }finally{await context.close();await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
