"use strict";
const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");
const root = path.resolve(__dirname,"..");
const read = file => fs.readFileSync(path.join(root,file),"utf8");
const html = read("index.html");
const ui = read("js/ui-individual-values.js");
const calc = read("js/billing-calculation.js");
const meter = read("js/ui-metering.js");
const transition = read("js/year-transition-actions.js");
const persistence = read("js/ui-master-data.js");
const css = read("assets/app.css");

assert.match(html,/id="manuellewerte"[\s\S]*id="individualKpis"[\s\S]*id="individualDynamicSections"[\s\S]*id="individualPriorTransferDialog"/);
assert.doesNotMatch(html.slice(html.indexOf('id="manuellewerte"'),html.indexOf('id="umlage"')),/individual-values-tabs|role="tablist"/i);
assert.match(ui,/individualValuePageModel\(state\)/);
assert.match(ui,/consumptionCosts\.map\(consumptionSection\)/);
assert.match(ui,/manualCosts\.map\(manualSection\)/);
assert.match(ui,/Gesamtverbrauch Wohnung/);
assert.match(ui,/Gesamtkosten laut „Gesamtkosten“/);
assert.match(ui,/Summe der erfassten Einzelwerte/);
assert.match(ui,/Rückleseprüfung|persistedSectionMatches/);
assert.match(ui,/parseLocaleNumber/);
assert.match(ui,/role === "private"[\s\S]*role === "vacancy"/);
assert.doesNotMatch(ui,/K002|Wasserversorgung|Heiz- und Warmwasserkosten/);
assert.doesNotMatch(ui,/localStorage|sessionStorage/);

assert.match(calc,/function individualValueCostKind/);
assert.match(calc,/normalizedIndividualKey\(cost\.umlageschluessel\) === "verbrauch"/);
assert.match(calc,/function individualConsumptionCosts/);
assert.match(calc,/function individualManualCosts/);
assert.match(calc,/function metersForIndividualCost/);
assert.match(calc,/String\(meter\.kostenId \|\| ""\) !== String\(costId \|\| ""\)/);
assert.match(calc,/complete \? group\.rows\.reduce[\s\S]*: null/);
assert.match(calc,/function manualCostSummary/);
assert.doesNotMatch(calc.slice(calc.indexOf("function inferManualInputMode"),calc.indexOf("function defaultManualInputMode")),/K002/);

assert.match(meter,/NKProMeteringDraft/);
assert.match(meter,/function setIndividualMeterDraftValue/);
assert.match(transition,/individualConsumptionCosts/);
assert.match(transition,/additions = normalized\.filter/);
assert.match(transition,/skipped:normalized\.length - additions\.length/);
assert.match(persistence,/Rückleseprüfung der gespeicherten Abrechnung fehlgeschlagen/);
assert.match(persistence,/storageIntegrityChecksum/);
assert.match(css,/AP22F10G-B/);
assert.match(css,/#manuellewerte \.individual-values-table-wrap[\s\S]*overflow-x:auto/);
assert.match(css,/#manuellewerte \.individual-values-table thead th[^{]*\{[^}]*background:[^;]+!important/);
assert.match(html,/99\.4\.58-ap22f10g-b/);
assert.match(read("service-worker.js"),/99\.4\.58-ap22f10g-b/);
console.log("AP22F10G-B static checks: PASS");
