"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const index=read("index.html");
const css=read("assets/app.css");
const ui=read("js/ui-individual-values.js");
const calc=read("js/billing-calculation.js");
const workflow=read("js/billing-workflow.js");
const metering=read("js/ui-metering.js");
const master=read("js/meter-master.js");
const transition=read("js/year-transition-actions.js");
const quality=read("js/quality-rules.js");
const start=index.indexOf('<section class="tab" id="manuellewerte">');
const end=index.indexOf('<section class="tab"',start+1);
assert.ok(start>0&&end>start,"section#manuellewerte fehlt");
const page=index.slice(start,end);
assert.equal((page.match(/data-individual-kpi="/g)||[]).length,4,"Es müssen exakt vier Kennzahlenkacheln vorhanden sein");
for(const key of ["water-total","water-meters","external-total","cost-match"])assert.match(page,new RegExp(`data-individual-kpi="${key}"`));
assert.match(page,/individual-values-kpi__icon--heat[\s\S]*?<svg[\s\S]*?<path[^>]+>/,"Rotes Linien-Flammensymbol fehlt");
assert.doesNotMatch(page,/individual-values-kpi__icon--heat[\s\S]{0,250}(?:€|EUR)/,"Eurozeichen darf nicht Hauptsymbol der Heizkostenkachel sein");
assert.match(page,/id="individualWaterTable"/);
assert.match(page,/id="individualExternalSections"/);
assert.match(page,/id="individualPriorTransferDialog"/);
assert.match(page,/id="individualWaterEditDialog"/);
assert.match(page,/id="individualExternalImportDialog"/);
assert.doesNotMatch(page,/sortable|sort-asc|sort-desc/,"Unechte Sortiermerkmale sind unzulässig");
assert.match(css,/\/\* AP22F10B/);
const scoped=css.slice(css.indexOf("/* AP22F10B"),css.indexOf("/* AP22F9B"));
assert.ok(scoped.length>5000,"AP22F10B-CSS-Block fehlt");
for(const line of scoped.split(/\r?\n/)){if(!line.includes("{")||line.trim().startsWith("/*")||line.trim().startsWith("@media"))continue;assert.ok(line.includes("#manuellewerte"),`Nicht seitenbezogener AP22F10B-Selektor: ${line}`);}
assert.match(scoped,/#manuellewerte \.individual-values-kpis\{[^}]*grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);
assert.match(scoped,/@media\(max-width:1100px\)[\s\S]*?#manuellewerte \.individual-values-kpis\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
assert.match(scoped,/#manuellewerte \.individual-values-table-wrap\{[^}]*overflow-x:auto/);
assert.match(scoped,/#manuellewerte \.individual-values-table thead th\{[^}]*background:var\(--nk-ui-color-surface-muted/);
assert.match(scoped,/#manuellewerte .*:focus-visible/);
assert.doesNotMatch(scoped,/thead[^}]*background:(?:#0|#1|navy|green|yellow)/i);
assert.match(calc,/function individualValueCases\(/);
assert.match(calc,/role:"vacancy"/);
assert.match(calc,/function waterConsumptionSummary\(/);
assert.match(calc,/Math\.abs\(difference\) <= tolerance/);
assert.match(calc,/const explicitMode = input && \["Direkter Eurobetrag", "Externe Einzelabrechnung", "Verbrauchsmenge"\]/);
assert.match(workflow,/input\.caseValues/);
assert.match(workflow,/allowedFields = \["amount", "consumption", "provider", "recordedAt", "note"\]/);
assert.match(metering,/setManualCanonicalReading/);
assert.match(master,/ohne[\s\S]{0,80}künstlichen Mieterdatensatz/);
assert.match(transition,/prepareIndividualPriorReadingTransfer/);
assert.match(transition,/already-transferred/);
assert.match(transition,/status = "ambiguous"/);
assert.match(transition,/status = "assignment-changed"/);
assert.match(transition,/Vorjahresendstände wurden nicht automatisch übernommen/);
assert.match(quality,/NKP-PLAU-006/);
assert.match(quality,/NKP-PLAU-012/);
assert.match(quality,/tolerance:\.01/);
assert.doesNotMatch(ui,/localStorage|sessionStorage|indexedDB|NKProPersistence|commitStateChange\(/,"UI-Modul darf nicht direkt persistieren");
assert.match(ui,/NKProApplicationActions\.execute/);
assert.match(ui,/Abrechnungsfall mehrfach enthalten/);
console.log("AP22F10B Individuelle Werte static: PASS");
