const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname,'..');
const ui = fs.readFileSync(path.join(root,'js/ui-individual-values.js'),'utf8');
const html = fs.readFileSync(path.join(root,'index.html'),'utf8');
const css = fs.readFileSync(path.join(root,'assets/app.css'),'utf8');
assert.ok(ui.includes('data-individual-water-end'));
assert.ok(ui.includes('data-individual-water-batch-save'));
assert.ok(ui.includes('saveWaterBatch'));
assert.ok(ui.includes('data-individual-external-inline'));
assert.ok(ui.includes('data-individual-external-batch-save'));
assert.ok(ui.includes('Heiz- und Warmwasserzubereitungskosten erfassen'));
assert.ok(ui.includes('pendingWater'));
assert.ok(ui.includes('pendingExternal'));
assert.ok(css.includes('AP22F10F'));
assert.ok(html.includes('V99.4.56'));
console.log('AP22F10F Sammelerfassung static: PASS');
