"use strict";
const assert=require("node:assert/strict");
const crypto=require("node:crypto");
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const sha=value=>crypto.createHash("sha256").update(value).digest("hex");
const html=read("index.html");
const css=read("assets/app.css");
const nav=read("js/ui-navigation-pages.js");
const controller=read("js/ui-page-controller.js");
function extractSection(source,id){const start=new RegExp(`<section\\b[^>]*\\bid=["']${id}["'][^>]*>`,"i").exec(source);assert.ok(start,`section#${id} fehlt`);const tags=/<\/?section\b[^>]*>/ig;tags.lastIndex=start.index+start[0].length;let depth=1,m;while((m=tags.exec(source))){depth+=m[0][1]==="/"?-1:1;if(!depth)return source.slice(start.index,tags.lastIndex);}throw new Error(`section#${id} unvollständig`);}
const start=extractSection(html,"start");
assert.equal((start.match(/<h1\b/gi)||[]).length,1,"start benötigt genau ein H1");
assert.equal((start.match(/id="startArchiveTable"/g)||[]).length,1,"start benötigt genau eine führende Tabelle");
assert.match(start,/class="billing-overview-card nk-ui-card"/,"führende Tabellenkarte fehlt");
assert.match(start,/id="billingOverviewSearch"/,"Suche fehlt");
assert.match(start,/data-billing-overview-filter="all"[\s\S]*data-billing-overview-filter="current"[\s\S]*data-billing-overview-filter="archive"/,"Bestandsfilter fehlen");
assert.doesNotMatch(start,/data-area-dashboard="billing"|dashboard-process|dashboard-fact/,"Prozessdashboard ist noch auf start vorhanden");
assert.doesNotMatch(start,/<button[^>]*data-ui-action="system\.runSelfTest"/,"App-Selbsttest darf nicht als bedienbare Aktion im normalen Startseitenfluss stehen");
assert.match(start,/<span[^>]*data-ap22f6b-diagnostics-compat[^>]*hidden/,"unsichtbarer Diagnostik-Kompatibilitätsmarker fehlt");
assert.doesNotMatch(start,/data-ui-action="archive\.deleteAt"|billing\.openDeleteModal/,"Löschaktion darf nicht auf start erscheinen");
assert.match(start,/billing-overview-table-shell/,"interne Tabellen-Overflow-Hülle fehlt");
assert.match(start,/billing-readonly-notice|billing-overview-content/,"normaler Dokumentfluss fehlt");
const context=html.match(/<section aria-label="Abrechnungskontext"[\s\S]*?<\/section>/)?.[0]||"";
assert.ok(context,"Kontextleiste fehlt");
assert.doesNotMatch(context,/Modus|data-global-billing-mode/i,"Kontextleiste enthält eine Modusangabe");
const head=nav.match(/const head='([^']|'[^;])*?<\/thead>';/)?.[0]||nav;
for(const label of ["Abrechnung","Objekt","Status","Arbeitsstand","Zuletzt bearbeitet","Saldo","Aktionen"])assert.match(nav,new RegExp(`<th[^>]*scope="col"[^>]*>${label}`),`Spalte ${label} fehlt`);
assert.match(nav,/billingOverviewGroupBody\("current","Aktuelle Abrechnung"/);
assert.match(nav,/billingOverviewGroupBody\("archive","Archivierte Abrechnungen"/);
assert.match(nav,/data-icon-only="true"/,"Icon-only-Kennzeichnung fehlt");
assert.match(nav,/title="' \+ escapeHtml\(label\) \+ '" aria-label="' \+ escapeHtml\(label\) \+ '"/,"title und aria-label sind nicht identisch gebunden");
assert.match(nav,/<svg aria-hidden="true"/,"dekorative SVG-Semantik fehlt");
assert.match(nav,/billingOverviewActionButton\("Bearbeiten", "edit", "billing\.openCurrentEdit"\)[\s\S]*billingOverviewActionButton\("Ansehen", "view", "billing\.openCurrentView"\)/,"Aktionsreihenfolge Bearbeiten/Ansehen abweichend");
assert.match(nav,/billingOverviewActionButton\("Abschließen", "finalize", "billing\.finalize"\)/);
assert.match(nav,/billingOverviewActionButton\("Archivieren", "archive", "archive\.currentYear"\)/);
assert.match(nav,/billingOverviewActionButton\("Archiv aktualisieren", "refresh", "archive\.currentYear"\)/);
assert.match(nav,/billingOverviewActionButton\("Zur Korrektur öffnen", "edit", "archive\.reopenForRework"/);
assert.doesNotMatch(nav,/billingOverviewActionButton\([^\n]+delete|billingOverviewActionButton\("Löschen"/i);
assert.match(css,/#start \.billing-actions\{[^}]*flex-wrap:nowrap[^}]*white-space:nowrap/,"Aktionsgruppe darf nicht umbrechen");
assert.match(css,/#start \.billing-overview-action\{[^}]*width:34px!important;height:34px!important/,"quadratische Symbolbuttons fehlen");
assert.match(css,/#start \.billing-overview-action:focus-visible\{[^}]*outline:/,"sichtbarer Tastaturfokus fehlt");
assert.match(css,/#start \.billing-overview-action:disabled[^}]*cursor:not-allowed/,"deaktivierter Zustand fehlt");
assert.match(css,/#start \.billing-overview-table-shell\{[^}]*overflow-x:auto/,"interner Tabellen-Scroll fehlt");
assert.match(css,/@media\(max-width:620px\)/,"620-px-Regeln fehlen");
assert.match(css,/@media\(max-width:420px\)/,"390-px-nahe Regeln fehlen");
const prefix=Buffer.from(css,"utf8").subarray(0,291694);
assert.equal(sha(prefix),"09f71132f6db4537427f625412a21b6543271a9fc49b43cdec51b37d3774e471","bestehender CSS-Präfix wurde verändert");
assert.match(controller,/const AP17_DASHBOARD_TABS = Object\.freeze\(\["objektuebersicht"\]\)/,"start darf nicht mehr als Prozessdashboard gerendert werden");
assert.match(controller,/workPackage:"AP22F6B"/);
const pkg=JSON.parse(read("package.json"));
assert.equal(pkg.dependencies?Object.keys(pkg.dependencies).length:0,0,"neue Laufzeitabhängigkeit unzulässig");
const runtimeConfig=read("js/app-runtime-config.js");
assert.match(runtimeConfig,/DATA_SCHEMA_VERSION\s*=\s*5/,"Datenschema 5 muss erhalten bleiben");
console.log("AP22F6B billing overview static: PASS");
