const fs = require("fs");
const path = require("path");
const vm = require("vm");
const assert = require("assert");
const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const context = { console, structuredClone:global.structuredClone };
context.globalThis = context;
vm.createContext(context);
vm.runInContext(read("js/application-actions.js"), context);
let value = 0;
context.NKProApplicationActions.configure({ object:{ setName:name => { value = name; return value; } }, billing:{ finalize:() => "ok" } });
assert.equal(context.NKProApplicationActions.execute("object", "setName", ["Haus A"]).value, "Haus A");
assert.equal(value, "Haus A");
assert.equal(context.NKProApplicationActions.describe().actionCount, 2);
assert.throws(() => context.NKProApplicationActions.execute("object", "missing"), /Unbekannte/);
const actions = read("js/application-actions.js");
assert(!/document\.|querySelector|localStorage|sessionStorage/.test(actions), "Anwendungsschicht darf weder DOM noch Browser-Speicher kennen.");
const bindings = read("js/ui-bindings.js");
assert(bindings.includes('appCall(applicationActions, "object"'), "Objektcontroller muss Anwendungsschicht verwenden.");
assert(bindings.includes('appCall(applicationActions, "billing"'), "Billingcontroller muss Anwendungsschicht verwenden.");
assert(bindings.includes('appCall(applicationActions, "meter"'), "Zählercontroller muss Anwendungsschicht verwenden.");
const html = read("index.html");
assert(html.indexOf("js/application-actions.js") < html.indexOf("js/app.js"), "Anwendungsaktionen müssen vor app.js geladen werden.");
const worker = read("service-worker.js");
assert(worker.includes('./js/application-actions.js'), "Anwendungsschicht muss Teil der App-Shell sein.");
process.stdout.write("AP8-Anwendungsaktionsprüfung abgeschlossen: explizite Anwendungsschicht, kontrollierte UI-Anbindung und DOM-/Speicherfreiheit sind konsistent.\n");
